apiVersion: batch/v1
kind: Job
metadata:
  name: pulseforge
  namespace: pulseforge
spec:
  template:
    spec:
      containers:
        - name: pulseforge
          image: pulseforge:0.1.0
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
