replicaCount: 1

image:
  repository: pulseforge
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  port: 8080

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 128Mi
